
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author prachim89
 */
public class TranslateUI extends javax.swing.JFrame {
    String selectedLang1="";
    String selectedLang2="";
    String text1 = "";
    String text2 = "";
    TranslateService myService;
    Language language;
    
    /**
     * Creates new form TranslateUI
     */
    public TranslateUI() {
      
      myService = new TranslateService();
      language = new Language();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lang1 = new javax.swing.JComboBox();
        lang2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        send1 = new javax.swing.JButton();
        error1 = new javax.swing.JButton();
        send2 = new javax.swing.JButton();
        error2 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        rateApp = new javax.swing.JButton();
        save2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lang1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Albanian", "Arabic", "Azerbaijani", "Basque", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "ChineseSimplified", "ChineseTraditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "HaitianCreole", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));

        lang2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Afrikaans", "Albanian", "Arabic", "Azerbaijani", "Basque", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "ChineseSimplified", "ChineseTraditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "HaitianCreole", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        lang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lang2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Language 1");

        jLabel2.setText("Language 2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        send1.setText("Send");
        send1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send1ActionPerformed(evt);
            }
        });

        error1.setText("Error");
        error1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                error1ActionPerformed(evt);
            }
        });

        send2.setText("Send");
        send2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send2ActionPerformed(evt);
            }
        });

        error2.setText("Error");
        error2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                error2ActionPerformed(evt);
            }
        });

        save1.setText("Save");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });

        rateApp.setText("Rate This App");
        rateApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateAppActionPerformed(evt);
            }
        });

        save2.setText("Save");
        save2.setToolTipText("");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(send1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(save1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(error1))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lang1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(send2)
                                .addGap(16, 16, 16)
                                .addComponent(save2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(error2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lang2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rateApp)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(send1)
                    .addComponent(error1)
                    .addComponent(send2)
                    .addComponent(error2)
                    .addComponent(save1)
                    .addComponent(save2))
                .addGap(45, 45, 45)
                .addComponent(rateApp))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send1ActionPerformed
        // TODO add your handling code here:
        selectedLang1 = language.Languages.get(lang1.getSelectedItem());
        selectedLang2 = language.Languages.get(lang2.getSelectedItem());
        text1 = jTextArea1.getText();
        if(selectedLang1.equalsIgnoreCase(selectedLang2)){
            jTextArea2.setText(text1);
        }
        else{
        try{
        String translatedText1 = myService.translate(text1,selectedLang2,selectedLang1);
        jTextArea2.setText(translatedText1);
        
        }
        catch(IOException ioe){
            System.out.print("IOException caught");
        }
        }
    }//GEN-LAST:event_send1ActionPerformed

    private void error1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_error1ActionPerformed
        // TODO add your handling code here:
        selectedLang2 = language.Languages.get(lang2.getSelectedItem());
        text1 = "Could not understand. Please enter again";
         
            String translatedText2 = "";
            if("en".equalsIgnoreCase(selectedLang2)){
               jTextArea2.setText(text1);
            }
            else{
                try{
        translatedText2 = myService.translate(text1,selectedLang2,"en");
        jTextArea2.setText(translatedText2);
        
        }
        catch(IOException ioe){
            System.out.print("IOException caught");
        }
            }
    }//GEN-LAST:event_error1ActionPerformed

    private void lang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lang2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lang2ActionPerformed

    private void send2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send2ActionPerformed
        // TODO add your handling code here:
        selectedLang1 = language.Languages.get(lang1.getSelectedItem());
        selectedLang2 = language.Languages.get(lang2.getSelectedItem());
        text2 = jTextArea2.getText();
        if(selectedLang1.equalsIgnoreCase(selectedLang2)){
            jTextArea1.setText(text2);
        }
        else{
        try{
        String translatedText2 = myService.translate(text2,selectedLang1,selectedLang2);
        jTextArea1.setText(translatedText2);
        
        }
        catch(IOException ioe){
            System.out.print("IOException caught");
        }
        }
    }//GEN-LAST:event_send2ActionPerformed

    private void error2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_error2ActionPerformed
        // TODO add your handling code here:
        selectedLang1 = language.Languages.get(lang1.getSelectedItem());
        text2 = "Could not understand. Please enter again";
        
            String translatedText1 = "";
            if("en".equalsIgnoreCase(selectedLang1)){
               jTextArea1.setText(text2);
            }
            else{
                try{
        translatedText1 = myService.translate(text2,selectedLang1,"en");
        jTextArea1.setText(translatedText1);
        
        }
        catch(IOException ioe){
            System.out.print("IOException caught");
        }
            }
    }//GEN-LAST:event_error2ActionPerformed

    private void rateAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateAppActionPerformed
        // TODO add your handling code here:
        try {
   //Set your page url in this string.
         String url = "https://ufl.qualtrics.com/SE/?SID=SV_7WXjWKJESjOujYx";
         java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
       }
       catch (java.io.IOException e) {
           System.out.println(e.getMessage());
       }
    }//GEN-LAST:event_rateAppActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
        // TODO add your handling code here:
        CreateFile saveToFile = new CreateFile();
        saveToFile.SaveAs(jTextArea1);
    }//GEN-LAST:event_save1ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        // TODO add your handling code here:
        CreateFile saveToFile = new CreateFile();
        saveToFile.SaveAs(jTextArea2);
    }//GEN-LAST:event_save2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranslateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranslateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranslateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranslateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TranslateUI go = new TranslateUI();
                go.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                go.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton error1;
    private javax.swing.JButton error2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox lang1;
    private javax.swing.JComboBox lang2;
    private javax.swing.JButton rateApp;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JButton send1;
    private javax.swing.JButton send2;
    // End of variables declaration//GEN-END:variables
}
